0x0C-web_server

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -4,15 +4,18 @@
 
 ./1-install_nginx_web_server
 
-cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
-
-REDIRECTION_CONFIG="\
-location /redirect_me {
+read -r -d '' redirect_rule <<'EOF'
+location /redirect_me/ {
     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
-}"
+}
+EOF
 
-sed -i '/server {/a '"$REDIRECTION_CONFIG"'' /etc/nginx/sites-available/default
+if [ -f /etc/nginx/sites-available/default ]; then
+    cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
+    awk -v r="$redirect_rule" '/server_name _;/ {print; print r; next} 1' /etc/nginx/sites-available/default > /etc/nginx/sites-available/default.tmp && mv /etc/nginx/sites-available/default.tmp /etc/nginx/sites-available/default
+else
+    echo "Default server block configuration file not found"
+    exit 1
+fi
 
-nginx -t
-
-service nginx restart
+service nginx reload
